# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives

In this lab you will: 

- Find the shape of vectors and matrices 
- Access and manipulate individual scalar components of a matrix 
- Create vectors and matrices using Numpy and Python

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [1]:
import numpy as np

In [2]:
A = np.array([[1402, 191], [1371, 821], [949, 1437], [147, 1448]])
B = np.array([[1, 2, 3], [4, 5, 6]])

print('A:\n', A)
print('B:\n', B)

A:
 [[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
B:
 [[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of $A$ and $B$ 

In [3]:
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)

Shape of A: (4, 2)
Shape of B: (2, 3)


## 3. Print elements from $A$

Print the following elements from $A$: 

* First row and first column
* First row and second column
* Third row and second column
* Fourth row and first column

In [4]:
print(A[0, 0])
print(A[0, 1])
print(A[2, 1])
print(A[3, 0])

1402
191
1437
147


## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10 

In [5]:
C = np.zeros((3,3))
for i in range(C.shape[0]):
    for j in range(C.shape[1]):
        C[i,j] = np.random.randint(10)
C

array([[1., 6., 5.],
       [3., 5., 0.],
       [3., 1., 4.]])

In [6]:
# Or more simply:
C = np.random.randint(10, size=(3,3))
C

array([[8, 9, 7],
       [3, 5, 6],
       [7, 5, 5]])

## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero-valued matrices and fill with random data using the function
* Add the matrices together in Numpy 
* Print the results

In [7]:
def fill_matrix(matrix):
    """Takes a numpy 2D matrix as input, and fills it with random integers."""
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            matrix[i,j] = np.random.randint(10)
            
D = np.zeros((4,4))
E = np.zeros((4,4))

for matrix in [D, E]:
    fill_matrix(matrix)
    
F = D + E
F

array([[ 6.,  7.,  9.,  7.],
       [13.,  5.,  8., 12.],
       [12., 11.,  3.,  9.],
       [18., 10.,  8.,  7.]])

## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in Numpy. We shall now move forward to learning more complex operations including dot products and matrix inversions.  